name: nyan_cat_war
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  html: ^0.15.4
  path_provider: ^2.1.2
  path: ^1.8.3
  audioplayers: ^5.2.1
  provider: ^6.1.1
  firebase_core: ^2.25.3
  firebase_database: ^10.4.4
  youtube_player_flutter: ^9.0.0
  volume_control: ^0.1.5
  just_audio: ^0.9.38
  audio_service: ^0.18.13
  get_it: ^7.7.0
  audio_video_progress_bar: ^2.0.3
  flutter_image: ^4.1.11
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bgm/
    - assets/stage_images/
    - assets/stage_images/超獣ステージ/

flutter_icons:
  android: true
  ios: true
  image_path: "/Users/muratareo/Desktop/nyan_cat_war/assets/gokuenki.png"